sudo: required
dist: trusty
notifications:
  email: false
language: node_js
node_js:
  - '8'
before_install:
  - npm install -g npm
jobs:
  include:
    - stage: tests
      cache:
        directories:
          - frontend/node_modules
      install:
        - cd frontend
        - npm install
      script:
        - npm test
    - stage: tests
      cache:
        directories:
          - backend/node_modules
      before_install:
        - >
            printf "version: '2'\n\nservices:\n  db:\n    image: postgres:10\n    ports:\n      - '5321:5432'\n    environment:\n      - POSTGRES_USER=disa\n      - POSTGRES_PASSWORD=citest\n      - POSTGRES_DB=disa_test_db\n    volumes:\n      - ./disa_pgdata:/var/lib/postgresql/data\n    container_name: disa_db" > docker-compose.yml
        - docker-compose up -d
      install:
        - cd backend
        - npm install
      script:
        - npm run test-ci
      env:
        - TEST_DB_NAME=disa_test_db
        - DB_USER=disa
        - DB_PASS=citest
        - DB_HOST=localhost
        - DB_PORT=5321
        - SECRET=Ir8CG7mwPJr3lh1yhpIGqW1jzhFbH4fzsxtcdmdC9MTy6Z7GVTlUvw3a1y7eh8tx0jEm9ie2hMRyOW6PY3IvbQH21JtIqVcqiTla
services:
  - docker
after_success:
  - cd ..
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker build -t toska/disa-tool:staging ."
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_BRANCH =~ (^master) ]] && docker push toska/disa-tool:staging"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker build -t toska/disa-tool:latest ."
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker push toska/disa-tool:latest"
