sudo: true
dist: trusty
cache:
  directories:
    - frontend/node_modules
    - backend/node_modules
notifications:
  email: false
language: node_js
node_js:
  - '8'
before_install:
  - npm install -g npm
  - >
    printf "version: '2'\n\nservices:\n  db:\n    image: postgres:10\n    ports:\n      - '5321:5432'\n    volumes:\n      - ./disa_pgdata:/var/lib/postgresql/data\n    container_name: disa_db" >> docker-compose.yml
  - docker-compose up -d
  - sleep 5
  - docker exec -u postgres disa_db psql -c "CREATE DATABASE disa_test_db"
install:
  - cd frontend
  - npm install
  - cd ../backend
  - npm install
  - cd ..
jobs:
  include:
    - stage: tests
      script:
        - cd frontend
        - npm test
        - cd ..
    - stage: tests
      script:
        - cd backend
        - npm test
        - cd ..
      env:
        - TEST_DB_URL=postgres://postgres@localhost:5321/disa_test_db
        - SECRET=Ir8CG7mwPJr3lh1yhpIGqW1jzhFbH4fzsxtcdmdC9MTy6Z7GVTlUvw3a1y7eh8tx0jEm9ie2hMRyOW6PY3IvbQH21JtIqVcqiTla
